<!doctype html>
    <head>
	  <?php require '/home/public/head.php';?>
	  <link rel="stylesheet" type="text/css" href="/css/dateHeaderStyling.css">
      <title>Journal</title>
    </head>
    <body>
        <div class="header-container">
            <header class="wrapper clearfix">
              <h1 class="title">JOURNAL</h1>
            </header>
        </div>

        <div class="main-container">
          <nav>
		    <?php require '/home/public/navBarTemplate.php';?>
		  </nav>
		  <div>
			<article>
			  <h1 class="dateHeader"><time datetime="2018-10-31 20:23:00">Wednesday, October 31, 2018</time></h1>
			  <p>This is the new online journal I'll be keeping. ihaveconsideredwritingallofmyentrieslikethisinordertofoolthesnoopingonlinerobotsandthings but I guess I don't care that much so for now I will probably just write normally. 
				
				I'm tired. Today I went to the one? week follow up since my first dr appt since early 2017. it was mostly fine results.
				
				I am going to create an online checklist to help keep me motivated to do anything at all. I guess I can post my research here. That would feel extra motivational I think.
				
				we'll see what all else i'll do around here and on lmmportfolio.com. Oh yeah I need to post my resume there and to do that I would like to update my resume and to do that I need to find the resume i submitted in order to get my current job.
				
				know that i am aware that i am neglecting good punctuation and stuff while i write this. i'm mostly just trying to get thoughts down before i lose them.
				
				i'm gonna zone out with netflix and start research now. it's 8:22 pm.</p>
			  </article>
			  <article>
			  <h1 class="dateHeader"><time datetime="2018-11-02 11:07:37">Friday, November 2, 2018</time></h1>
			  <p>i just woke up from a nap that spanned some number of hours since this morning. It is now 1:34 pm, I took a sick day from work, and, in spite of the long nap, I have woken up to a headache?! I wonder what my blood pressure is right now.
				
				Okay 2:05 pm it's gone. Nice.
				
				Watching the new Sabrina the Teenage Witch story on Netflix for now. Shae says <u>Bitch</u> magazine likes it. I should look that up for us now!
				
			  <a href="https://www.bitchmedia.org/article/chilling-adventures-sabrina-netlifx">Link to the article!</a> AND here is a nice bunch of text from the article that I like as a kind of summary:
				
			  <blockquote><i>Amidst fratricide, cannibalism, Baphomet’s hooves, hexes, demonic possessions, and chants of “Hail Satan,” The Chilling Adventures of Sabrina still offers viewers, what- and whoever they worship, an alternative to a world still propping up patriarchy, white supremacy, and other systems that limit and damage us. Even when the show is difficult to watch, the discomfort it evokes is necessary. The horror of the series lies not in its depiction of witchcraft or Satanism, but in the way it mirrors our current political climate, our nation’s inability to come to terms with its puritanical past, and the ways in which those who confront hypocrisy are coerced into silence.

                The character of Sabrina has always served as something of a role model for young women navigating the perplexing and often unfair imperatives of teen girlhood, but Netflix’s update is much more than that. Like Hecate, Lilith, Isis, and Persephone, Sabrina is divine in her own right, and the voice of this dark, provocative, and unnerving show sounds to me like a call to arms.</i></blockquote>
				
				Before I forget, I should also mention the other things I am working on for my site and this blog/journal thang!
			  <ul>
			    <li>powershell functions to make writing these entries easier. using the datetime html tag for example will be easier with powershell timestamps.</li>
				  <ul>
				    <li><code>Get-Date -Format "yyyy-MM-dd hh:mm:ss"</code></li>
				  </ul>
			  </ul>
			  </p>
			  </article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-03 04:40:46">Saturday, November 03, 2018</time></h1><p>Take 3!<br>I guess I'll have to use the break tag for this get-blogentry function until I possibly figure out a way to allow for shift+enter as a way to start a new line in a blog post. anyway, let me quickly retype what I was writing before I messed this post up in the first 2 tests of this new get-blogentry function :): <br>I was recommended a show called <u>Homecoming</u>.
                So far I guess it's pretty interesting. This is also my first test of the new PowerShell module I finished today for making it easier(?) to write the html entires for this blog. :) We'll see how well it works as soon as I DO NOT PRESS ENTER :P I learned that lesson by making that mistake during the first test.<br><br>Maybe later I'll post some fun or funny links or memes or something. I would really like to start knocking out items on some very old and long to do lists that I would also like to get published here on my site to make it more fun for me to get stuff done and get me back on this site doing useful things while I can't make myself/am too afraid to use the training materials from work. More later today, probably!</p></article>
              <article><h1 class="dateHeader"><time datetime="2018-11-03 08:10:05">Saturday, November 03, 2018</time></h1><p>Still watching the show while I try to work out some of the kinks in my new PS module. :)<br></p></article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-03 09:44:00">Saturday, November 03, 2018</time></h1><p>This should be my final test tonight. I want to be sure that the spacing looks good between the date title and the content. Just finished moving the to do list to the right place and updating index to point there. Yay, progress!</p></article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-04 02:32:55">Sunday, November 04, 2018</time></h1><p>I wanted to be sure I get down the URL that helped me find the new checks and boxes for the site!<br><a href="http://www.amp-what.com/unicode/search/checkbox">Link to www.amp-what.com</a><br>I am also considering figuring out a way to consolidate entries that happen on the same day so that the same day is not repeated for visitors to see over and over. <i>I kind of hate the repeating date that is happening right now</i>.<br>I can also clearly see that I have introduced a bug into the get-pasteable... function in the bloggingModule argh! I should probably kill two birds with one stone and fix the "repeating day" and "borked get-pasteable... function" problem with the same fix. The fix I have in mind will involve keeping a temp file around for the entire day; maybe I will create a private function that erases or resets the temp file for each different day.</p></article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-04 09:44:06">Sunday, November 04, 2018</time></h1><p>Oh man, this is test 5 now! I just made a change to the copy-blogentryhtml function that I hope will make it copy my entries finally; up until now, the set-clipboard or whatever command has not been working as advertised and my testing of each function showed that the copy-blogentryhtml function is where things fail sooo here we are! Anyway, previous entries not yet published to blog/journal/thingy below.<br><br>This is test 4, where I am actually testing out each of the previously un-exported module functions one by one to see which ones work or do not work. Let's see what happens! Still watching season 2 of "Are You Afraid of the Dark" and still enjoying its spooky 90s charm. Previous test entries below.<br><br>This is test 3, and I'm a little concerned now that there is some scope issue? Find previous tests below.<br><br>This is test 2.<br><br>Oh man, I just had to fix a bug where I accidentally left out the parameter so that the blog post was not being copied for paste later! Wowee! It is always suprising to see what one forgets when writing code.<br><br>I'm so grateful for PowerShell's long memory because it allowed me to easily recover my text for step 1, which I am goign to include below!<br><br>I just made a pretty big change to the bloggingModule that I hope will work fine. This is test one.<br><br>The change makes it so that just one function needs to be called in order to get to the part where you can just paste the new entry. :D I hadn't actually tested the new change to solve the broken function issue so this is a test of two changes. Oops?<br><br>I'm watching "Are You Afraid of the Dark" this morning. ^_^ Finally managed to start Season 2! For some reason, I was stuck in Season 1 before, basically since last night. Ha!</p></article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-04 10:03:42">Sunday, November 04, 2018</time></h1><p>Test of change where I just export the "onestep" function to abstract out the little helper functions that would be too hard to have memorized every time I want to make a post. Crossing my fingers and hoping this works as well as it should! Also hoping I used the word abstract correctly in this context! :P Fighting the urge to check the definition riiiiiight now.<br>update: I did use the word correctly according to <a href="https://whatis.techtarget.com/definition/abstraction">techtarget.com's definition</a>, and, the module is working exactly how I had hoped now! Success HUZZAH!!!!</p></article>
			  <article><h1 class="dateHeader"><time datetime="2018-11-04 11:43:24">Sunday, November 04, 2018</time></h1><p>Found what I needed to make the change that will consolidate entries for the same day under one day label! I did the research <a href="https://social.technet.microsoft.com/wiki/contents/articles/26009.getting-information-from-web-pages-via-powershell.aspx">here</a> and I recommend you read this if you have any interest in grabbing html from websites with PowerShell!</p></article>
			  <article><h1><time datetime="2018-11-04 05:07:24">Sunday, November 04, 2018</time></h1><p>Hey, here is another journal entry!<br><br>Watching Blackkklansmen(sp?) and just fixed the bloggingModule so that it checks for today in the journal; if it finds it, instead of creating an h1 tag with the day, it just puts in an hr tag to split different entries from the same day! Let's see if it works now. :)</p></article>
			  <hr><article><time datetime="2018-11-04 05:17:14"></time><p>test 2! there was a bug that I don't actually think I just fixed; I just rearranged the code around a test that worked when I was testing each line of the function by hand earlier. Let's see how this works and for how long (because I fully expect to find new bugs in this later) #yoloswag</p></article>
              <hr><article><time datetime="2018-11-04 05:23:58"></time><p>ALSO, I'm NOT going to go back through the journal to fix the repeating day headers previous to this fix since I want to keep some track of my previous failures that I learned from in creating this bloggy thing. :) NOICE! I am super excited to test this fix out tomorrow when the new header should be created for the new day. Yay!!!!! Cross your fingers and hope it works with me!</p></article>
              <hr><article><time datetime="2018-11-04 05:39:55"></time><p>I forgot to include the reference I used to find this newest solution, the hr tag! <a href="https://www.w3schools.com/tags/tag_hr.asp">Trusty w3schools lesson on hr!</a><br><br>But then in the same bunch of search results I found the first link in I found this other link that has some really useful detail about the hr tag I might like to use for later improvements and things! <a href="http://www.simplehtmlguide.com/divisions.php">simplehtmlguide's Sections, Divisions & Lines</a><br><br>Lastly, for good measure(?), here is the link to my search for information on this stuff. <a href="https://www.google.com/search?q=separator+html&oq=separator+html&aqs=chrome..69i57j0l5.113903j0j4&sourceid=chrome&ie=UTF-8">Search and its results that contain both previously mentioned references!</a></p></article>
              <hr><article><h1 class="dateHeader"><time datetime="2018-11-22 07:10:49">Thursday, November 22, 2018</time></h1><p>Happy Thanksgiving! I am looking into some CSS to spruce this place up. I happened to see <a href="https://www.athena.com.au/">this really cool site at a reddit link</a> and now I guess I'm feeling more inspired and ready to start working on some CSS for this site. &#128558; &#128539; I am also curious to see how these smilies I found at <a href="https://html-css-js.com/html/character-codes/icons/">html-css-js</a> look!<br>&#128013;<br>I really love these HTML character codes, which is apparently what these are called! Sssshhhhh too many exclamation points, I didn't mean to scream so much.<br><br>Oh, and the Mexico trip is coming up on Tuesday if I remember correctly. Gaw. I still need to get money for the trip, I think! I'll add that to my list and text S to ask her how much cash I should get. I'm pretty sure she already mentioned a reasonable amount that I have forgotten already. &#128579; &#128527; &#128518; &#127975; &#128178;&#128181; &#128184;&#128154;&#128176;<br>I think it might be a nice thing if I could come up with some fun little thing to make today and publish to git in addition to working on the CSS stuff. Oh man, I'm having trouble focusing. It is tough to prioritize because my internet is not working at my house since two days ago; I got home from work, went to turn on the old teevee, and, instead of getting to Netflix, I got a message saying I was not connected to the internet. Long story short, I called the IP and went through the remote troubleshooting process with them. When we saw the issue persist, he scheduled a technician to go to my place this Friday to check the situation out in person. The timing might be perfect since my mom and dad are also trying to start service with a different phone service provider within the next week or so. Golly.<br><br>Getting back to this site work, OH I forgot to mention that I tried getting back to Pluralsight trainng yesterday and ended up working on these IQ evaluators for different tech field subject things and so far I am not doing too terribly on, like, the Windows Server Admin(?) evaluations so far. :) It's pretty cool and fun bu tit takes more focus than I think I can give at the moment, given the current distractions and things. Ah, well, such is life, right?<br><br>OH I think I might start posting my scribbles and things on here, too. It gives me yet another way to feel like I am accomplishing something, probably. :D :) <br><br>O.M.G. I can make my own html characters with codes!!! :O :O :O For example, I could create my own icons for: <ul><li>margarita</li><li>pizza?</li><li>oh wow I could make xxx ones wow something to think about</li><li>loss lol</li></ul></p></article>
              <hr><article><h1 class="dateHeader"><time datetime="2018-12-09 08:22:55">Sunday, December 09, 2018</time></h1><p>I finally figured out how I want to fix my newly redesigned to do/done list in order to see the list different ways. What I can probably do is write a function (in javascript or something else? Maybe jquery? Not sure yet) that will hide items in the list depending on what the class is, active, success, or danger.<br><br>Anyway, it has been a pretty productive weekend. I have checked many things off of my to do list, including breaking out the code for the header, footer, and navigation bar for my site pages and using the require keyword to call the new, separate files in order to make the code more modular! I'm pretty proud and relieved that this was finally done.</p>
                <div class="row">
				  <div class="col-xs-3 col-lg-3"><h2>References</h2>
                  <ol>
                    <li><a href="https://www.w3schools.com/bootstrap/bootstrap_tables.asp">w3schools | Bootstrap Tables</a></li>
                    <li><a href="https://www.w3schools.com/bootstrap/bootstrap_grid_basic.asp">w3schools | Bootstrap Grids</a></li>
				    <li><a href="https://www.w3schools.com/php/php_includes.asp">w3schools | PHP 5 Include Files</a></li>
				    <li><a href="https://www.w3schools.com/php/php_syntax.asp">w3schools | PHP 5 Syntax</a></li>
				    <li><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article">&#60;article&#60;: The Article Contents element | MDN</a></li>
				  </ol></div><!--end of references column-->
				  <div class="col-xs-3 col-lg-3"><h2>Things I Would Like To Read Now</h2>
				  <ol>
				    <li><a href="http://www.the3spoons.com/blog/2017/2/14/the-unapologetic-paella">The Unapologetic Paella - The 3 Spoons</a></li>
					<li><a href="https://mommyshomecooking.com/venezuelan-mondongo/">VENEZUELAN MONDONGO SOUP [RECIPE+VIDEO] - Mommy's Home Cooking</a></li>
				  </ol></div><!--end of things to read asap-->
				  <div class="col-xs-3 col-lg-3"><h2>Plan to write code to change view of lists</h2>
				  <ol>
				    <li>
					  <h3>research jquery or javascript or bootstrap ways to select tr elements by class</h3>
					  <ol>
					    <li><a href="https://www.w3schools.com/jquery/jquery_selectors.asp">w3schools | the Class Selector</a></li>
					  </ol>
					</li>
					<li>
					  <h3>write new function in separate file with function to select tr elements by class</h3>
					  <ol>
					    <li><a href="https://www.w3schools.com/php/php_intro.asp">w3schools | PHP 5 Introduction</a></li>
						<li><a href="https://codepen.io/LMMGitUsername/pen/BREbem">my random trump quote machine was part of what reminded me to wait until page loads to take actions</a></li>
					  </ol>
					</li>
					<li>
					  <h3>research jquery or javascript or bootstrap ways to hide and show elements</h3>
					  <ol>
					    <li><a href="https://www.w3schools.com/jquery/jquery_hide_show.asp">w3schools | jQuery hide() and show()</a></li>
					  </ol>
					</li>
					<li>write new function in separate file with function to hide or show tr elements</li>
					<li></li>
				  </ol></div><!--end of algorithm-->
				  <div class="col-xs-3 col-lg-3"><h2>Things watched last week/over the weekend</h2>
				  <ol>
				    <li><a href="#">South Park episodes from latest season and/or member berry episode</a></li>
					<li><a href="#">The Good Place episode 9 IIRC</a></li>
					<li><a href="#">American Gods</a></li>
					<li><a href="#">District 9</a></li>
					<li><a href="#">Broad City</a></li>
					<li><a href="#">Dogs</a></li>
					<li><a href="#">Some New International Cooking Competition on Netflix now</a></li>
					<li><a href="#">D'Elia Standup?</a></li>
					<li><a href="#">Tom Segura Standup?</a></li>
					<li><a href="#">SNL this week and the ep with Justin Timberlake performing "D*** in a Box"</a></li>
					<li><a href="#">The Minimalists</a></li>
					<li><a href="#">Christopher Robin</a></li>
					<li><a href="#">Dumplin'</a></li>
					<li><a href="#">High Maintenance</a></li>
					<li><a href="#">Big Bang Theory</a></li>
					<li><a href="#">Young Sheldon</a></li>
					<li><a href="#">The Martian</a></li>
				  </ol></div><!--end of list of things watched recently-->
				</div><!--end of div class row 1-->
			  </article><!-- end of journal entry for Sunday, December 09, 2018 -->
			  <hr><article><h1 class="dateHeader"><time datetime="2018-12-13 12:02:41">Thursday, December 13, 2018</time></h1><p>It's been a while since I last wrote a journal entry. I got to go to a nice party tonight to celebrate a friend's birthday party. Nice!<br><br>I finally got to create a repository on GitHub for the PowerShell module I wrote to create these journal entries. Now that I've done that,<br><br><ul><li>I can finally access the module from any computer that I end up on (work or home)</li><li>I want to make changes to how the structure of the journal or the journal entries :)</li><li>I want to add a function to add these blog entries directly into the journal page</ul><br><br>At the same time, I also was able to do the same thing with my actual new site. Feels good!<br><br>Lastly, I just took a quick look back at the old entries to fix any typographical errors I could find. I found a cool issue due to a <a href="https://www.w3schools.com/html/html_entities.asp">reserved character</a> and found this great <a href="https://www.rapidtables.com/web/html/html-codes.html">HTML character code reference</a> to help fix it! <a href="https://www.w3schools.com/php/func_string_htmlspecialchars.asp">whooooaaa bonus forgotten reference!</a><br><br>Ha I forgot that I had to install Git on my work computer to be able to clone my PowerShell module and use it on my work computer. :) Then I had to remember how to do git stuff, which led me to these:<div><a href="https://help.github.com/articles/fetching-a-remote/">GitHub Help | Fetching a remote</a></div><a href="https://stackoverflow.com/questions/34713765/github-changes-repository-to-wrong-language>lol github called my site code Hack!</a> | <a href="https://hackernoon.com/how-to-change-repo-language-in-github-c3e07819c5bb">another reference related to GitHub and how it sees language<div><a href="https://git-scm.com/book/en/v2/Getting-Started-Installing-Git">Where I found the installer when I remembered I have to install Git in order to use it :P</a></div><div><a href=""></a></div><br><br>Okay it is too late to be up now I gotta go to bed bye!</p></article>
              <hr><article><time datetime="2018-12-13 07:31:44"></time><p>I'm nervous about the Portuguese language translation I have to do this morning for a colleague's WebEx. :\ It will be great practice BUT it will also surely be disheartening or humiliating. Oh well?<br><br>I also need to be sure to save the commands I used in Git to clone my remote repository to my computer here. :) I know I saved the link to the site where I found it buuuuut I think it will be really useful to have the full set of Git commands in one easy to remember place, too!<br><br><code>cd "C:\Users\lmartinez\Documents\lmmportfolioparty\powershell"<br>git clone https://github.com/LMMGitUsername/bloggingModule.git</code>
<br>And here are the commands I used to do the PowerShell part of things to clone the repo here on my machine:<br><code>$env:PSModulePath=$env:PSModulePath+";C:\Users\lmartinez\Documents\lmmportfolioparty\powershell"<br>$env:PSModulePath<br>Get-Module -ListAvailable<br>Import-Module bloggingModule<br>Get-BlogEntryOneStep<br>(Get-Date).ToLongDateString()</code></p></article>
<hr><article><h1 class="dateHeader"><time datetime="2018-12-14 06:02:49">Friday, December 14, 2018TESTOFPOWERSHELLCHANGE121418</time></h1><p>I learned that caching was preventing new css code from taking effect on the code of this site! THe cool thing about spending maybe approximately 2 hours fighting to make css work is that I learned about:<br><ul><li><a href="https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache">how to clear the browser cache in case the browser shows out of date information like it was for me yesterday</a></li><li><a href="https://css-tricks.com/child-and-sibling-selectors/">the child combinator selector in css</a></li></ul><br><br>I tried to read about using CSS with PHP in case I was doing that wrong and subsequently causing the issue that was preventing my new css from changing the look of things on the site (which is totally what was happening last night [and I totally started writing this entry last night but fell asleep while doing it so gave up until this morning]) but it was too much to try to begin to make sense of so I gave up. Thankfully, I remebered that caching can be a problem which led to the search that turned up the instructions for cache clearing that eventually allowed the new CSS to work. :)<br><br>Oh and I tried doing some research yesterday to see how I might write a function to auto-select an emoticon when I type ASCII faces. I even started a search for APIs but got discouraged by the results that I was seeing so decided to temporarily put that idea on the backburner. Meh.<br><br>I think the next item that I'd like to check of the old to do list is to make the nav bar sticky? We'll see.<br><br>I added the books I finished during the MX trip to my to do list, y'all. :P</p></article>
<hr><article><time datetime="2018-12-14 06:10:05"></time><p>One more thing for now: I had taken a break for a little while recently from using my bloggingModule to generate the HTML for these blog entries. It was at that time I was reminded that I apparently did not write the module such that it would spit out the long date string for the date when a blog entry for a new day is being written. ?!!??!?!? I can't believe I left it that way before so is it possible that there is a bug? I'm not sure. I'll check later. Maybe that will be the next thing that I fix for the site. Weeee shaaaaaall seeeeeeeeeeee.</p></article>
<hr><article><time datetime="2018-12-14 07:35:47"></time><p>this is a test of the change I just made to the bloggingModule so that it will automatically put an hr element between every journal entry regardless of datetime (which I am pretty sure it was not doing automatically before?) and put the class in the h1 element so that it formats the date stuff correctly for me. I can't believe I didn't write the module to do that before! Hopefully a nice difference between new entries and old entries shows. Let's see if this works!</p></article>
<hr><article><time datetime="2018-12-16 01:40:27"></time><p>I have changed quite a bit about the bloggingModule in the past two-ish days so this might be a long entry. :o :) :P<br><br><ul><li>I created a GUI for the bloggingModule! I am apparently successfully using that GUI to write this entry right now!</li><li>I added a manifest file to the newly updated blogging module.</li><li>I updated the list of to do earlier in the weekend if I remember correctly?</li></ul><br><br>I just realized that I do not and cannot save what I type here in the "Bloggule 1.0" and that it is hard to remember what all I have gotten done in the past couple of days or so. It is hard to list the things I've done. I think I have been thinking too hard without resting hard enough this weekend. Anyway,<br><br><ul><li>I added code to automatically insert the day string into the header for a new day's set of journal entries</li><li>I have suddenly gotten very tired of listing things!</li></ul><br><br>I have to admit that I am very anxious to see the final result of this test of these changes. I also want to check my to do list page to see what all I can mark as done, AND, I need to update my bloggingModule project on GitHub so that I can most easily update the bloggingModule on my home machine that I am not currently working from because I will be beyond upset if I lose the product of so much hard work and studying this weekend, gosh dangit. I am already super proud of what I did this weeked and past week but I'll be relieved and much prouder once I have this code backed up and on my home computer where I can eventually back it up on my own physical hardware, too.<br><br>Oh poo it feels so bad to end this journal entry right now in spite of my impatience to see the result of this test because currently my code files are full of the reference links from the research I have been doing over the past several days. I looked at a lot of cool stuff the past several days, y'all. :D</p></article>
<hr>
  <article>
  <h1><time datetime="2018-18-19 09:12:24">Wednesday, December 19, 2018</time>: The day that I fixed the bloggingModule bug that was preventing the h1 dateHeader HTML code from printing for any journal entries!</h1>
  <br><br>
  <aside><p>It is worth mentioning that, based on research today (references coming later), the structure of this journal or these journal entries is probably changing very soon!</p></aside><br><p>The following entries were created earlier today as part of the troubleshooting I have been doing of the bloggingModule. I went back through these entries from today to add in or move around datetime information and tags, again, based on things I have learned today.</p></aside><br>
  
  <hr><section><time datetime="2018-12-19 17:57:43">Wednesday, December 19, 2018</time><p>Been fighting with the PowerShell module all day (but really for two or three days since I first began to notice these bugs in the module) to fix the bug preventing me from running the module at all to test fixes to the other bug that has been preventing the module from spitting out correct html for journal entries being written for a day that doesn't already have the day written out in an h2 element. Although I am super pleased that I was finally able to get the module working again (which is another story in itself! Gaw, basically, to get the silly thing to work, I had to just point the 'shell directly at the directory where the module currently is, then, run a <code>Import-Module .\bloggingModule.psm1 -Force</code> to somehow force the <code>Get-BlogEntryOneStep -inGUI</code> command to become usable again!), now, I might be seeing yet another bug?! The textbox font for the gui looks wrong (?! bigger than expected!). Anyway, back to progress made: at least all of the module code is finally separated out into separate files as originally intended; I discovered, while debugging the code, that all of the separate module functions were written and apparently being used from within the one single .psm1 file, even though there were other files in the module folder. It's weird and confusing because at some unknown point in the past I had written almost all of the functions I saw in the module file in their own, separate file; what I had thought I had already done was write the module so that it used the separate files but what I was seeing was the same code in both the separate files and the module file. I couldn't believe that I had left it that way! I must have forgotten where I had left off in some previous testing of the separate functions. I really don't know. Anyway, I really want to wrap up this test to see if the h2 element is included this time. If it is, I think this might be the first time that the module does so successfully! Fingers crossed!</p></section>

<hr><section><time datetime="2018-12-19 17:57:44">Wednesday, December 19, 2018</time><p>second test. I forgot to mention in the first test entry today, I notice a new bug that is causing the bloggule gui to open without focus on the textbox. pressing OK earlier than I might usually since I am anxious to see if any of the latest fixes have made a helpful difference. Wish me luck!</p></section>

<hr><section><time datetime="2018-12-19 18:05:40">Wednesday, December 19, 2018 18:05:40</time><p>another quick test. as shown in newest snip from a little after 6 pm today, you can see the little "se" that appear in the command line after I click OK in the GUI. I wonder if the same thing occurs if I go the non gui route when running <code>Get-BlogEntryOneStep</code>?</p></section>

<hr><section><time datetime="2018-12-19 18:07:22">Wednesday, December 19, 2018, 18:07:22</time><p>bloop blorp another test just to see how things are working the non-gui route!</p></section>

<hr><section><time datetime="2018-12-19 18:16:24">Wednesday, December 19, 2018, 18:16:24</time><p>yet another quick little test after messing a little bit with bloggingModule.psm1 to see if I can finally get it to spit out an h2 element with the correct class! argh! still broken! bugs in the module continue to be discovered or created, troubleshot, and fixed, as I continue to not fix this persistent bug!</p></section>

<hr><section><time datetime="2018-12-19 18:25:00">Wednesday, December 19, 2018, 18:25:00</time><p>another little test. I hopefully made the test work so that it will show a true false value now instead of something that I guess is counting as null which is causing the else statement to always execute?</p></section>

<hr><section><time datetime="2018-12-19 18:28:58">Wednesday, December 19, 2018, 18:28:58</time><p>blee blah bug persists wah</p></section>
<h3>test code that saved my day and will fix the h1 bug for bloggingModule!</h3>
<code><br>
	<#test code below<br>
	&#36;u = "<URL>"<br>
	&#36;h = Invoke-WebRequest -Uri &#36;u<br>
	&#36;gltoj = (&#36;h.ParsedHtml.getElementsByTagName("h2") | Where{&#36;_.className -eq 'dateHeader'}).innerText | select -Last 1<br>
	Write-Host "get-lasttime... on the site says &#36;gltoj and the currentEntryHeader is &#36;currentEntryHeader so if statement for h2 placement should eval to &#36;(&#36;gltoj -match &#36;currentEntryHeader)"<br>
	end of test code#><br>
</code>
<hr><section><h3><time datetime="2018-12-19 18:49:00">Wednesday, December 19, 2018, 18:49:00</time></h3><p>another test now that I have used the result of the last test, which showed that my latest test change made the evaluation of the comparison of the two dates I was comparing do not match! I re-structured things with respect to the code for the helper function that looks at the date headers on my journal for html generating purposes. I'm using the command line for this test and am about to press enter so bye for now!</p></section>

<hr><section><h3><time datetime="2018-12-19 19:04:01">Wednesday, December 19, 2018, 19:04:01</time></h3><p>here is yet another journal entry slash test to see how my latest changes to the module may have either helped or hurt the situation. the latest change was atually to try just running all of the asterisk dot ps asterisk files in the blogging module dir to make sure that all functions should work in the current session. I cannot believe that with the latest logic changes in the bloggingModule that the header will not print still so I wonder seriously whether the problem is that old versions of functions are being used somehow. let's see how the result of runnign the bloggingmodule <code>get-blogentryonestep</code> command in the command line looks now! wish me luck!</p></section>

<hr><section><h3><time datetime="2018-12-19 19:13:43">Wednesday, December 19, 2018, 19:13:43</time></h3><p>it is possible i did not achieve the desired thing by running the previous command to quote unquote activate my ps functions and files and things the first time; I am hoping by that running in the command line <code>dir pipe where money underscore name hyphen match .ps bar for each money dot dot backslash dollar underscore</code> that I can do what I think might be possible to continue my debugging and testing correctly in case it has not been working correctly up until now. exciting stuff!</p></section>

<hr><section><h3><time datetime="2018-12-19 19:26:45">Wednesday, December 19, 2018, 19:26:45</time></h3><p>trying one more time in command line since messing again with the comparison code in the blogging module. I wrapped everything in dollar sign and parentheses since that was the only difference between my test and the code itself. let's see what happens!</p></section>

<hr><section><h2 class="dateHeader"><time datetime="2018-12-19 19:28:33">Wednesday, December 19, 2018, 19:28:33</time></h2><p>;alksja;lkjdsf</p></section>

<hr><section><h2 class="dateHeader"><time datetime="2018-12-19 21:03:05">Wednesday, December 19, 2018, 21:03:05</time></h2><p>finally fixed the header bug! this means that this entry should actually generate a nice big h2 header like the last one I just wrote while testing the latest fixes. :) Now, I can go pick up the prescription I have been neglecting in peace. I will wait until I get back from the pharmacy to click ok in this gui I am currently using. I'll write another entry later tonight. I think there are a few more minor or major bugs I would like to at least start thinking about tonight, before I leave for DFW for a week tomorrow.</p></section>

  <section>
    <h3>References:</h3><br>
	<ul>
	  <li><a href="https://www.toptal.com/designers/htmlarrows/currency/dollar-sign/">TopTal Dollar Sign HTML Codes</a>; Dollar sign HTML code found here.</li>
	  <li><a href="https://html.com/tags/article/">HTML.com &#60;article&#62; information</a>; really great example code here that illustrates well how to use the article tag with other tags that are new in HTML5.</li>
	  <li><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/heading_elements">"&#60;h1&#62;-&#60;h6&#62;: The HTML Section Heading Elements | MDN"</a>; has good related info, example code, and usage notes.</li>
	  <li><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article">&#60;article&#62;:The Article Contents element | MDN</a>; very useful usage notes and examples.</li>
	  <li><a href="https://www.w3schools.com/tags/tag_aside.asp">HTML aside Tag info from w3schools</a>; quick learnin' about the aside tag!</li>
	  <li><a href="https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines">Using HTML sections and outlines | MDN</a>; heading and sectioning in HTML5, basically. I will be reading this more thoroughly as I improve and edit the bloggingModule code to follow the rules being learned about today. This looks like a particularly good resource for my journaling purposes.</li>
	  <li><a href="https://www.google.com/search?q=nail+polish+dry+time&rlz=1C1CHBF_enUS760US760&oq=nail+polish+dry+time&aqs=chrome..69i57j0l5.6795j0j7&sourceid=chrome&ie=UTF-8">Search results for "nail polish dry time"</a>; I am also painting my nails today and am trying not to mess up the texture this time!</li>
	  <li><a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals">Fundamental text and font styling</a>"basic fundamentals of text/font styling in detail"</li>
	  <li><a href="http://rogerdudler.github.io/git-guide/">git - the simple guide</a>; how I was able to update my git remote bloggingModule repo tonight</li>
	  <li><a href="https://mcpmag.com/articles/2016/06/09/display-gui-message-boxes-in-powershell.aspx">How To Display GUI Message Boxes in PowerShell</a>; showed me how to just throw an alert dialog box up quickly and easily with just the one OK button</li>
	</ul>
	<h3>Things I Have Not Yet Used and Would Like to Read More About:</h3><br>
	<ul>
	  <li><a href="https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-html?view=powershell-6">ConvertTo-Html Information</a>; I tried this out quickly tonight and was fascinated! Need to read about and play with this more asap!</li>	  
	</ul>
  </section>
  <hr><article><h1 class="dateHeader"><time datetime="2018-12-20 2:04:14">Thursday, December 20, 2018 02:04:14</time></h1><p>A few of things I wanna say:<br>
<ul><li>bug with focus not being in textbox when bloggingModule ui opens is no longer occurring! Nice!</li><li>I have ended up tonight re-importing changes to my bloggingModule by using this command:<code>Import-Module .\bloggingModule.psm1 -Force</code></li><li>I added to/changed the css for my site. Neat!</li><li>I still need to update the github repo for the bloggingModule! Ack! Will I manage to get this done tonight? I'm not sure!</li></ul></p></article>
<hr><article><h1 class="dateHeader"><time datetime="2018-12-20 2:06:57">Thursday, December 20, 2018 02:06:57</time></h1><p>I think there is a new or persisting bug with the bloggingModule's ability to know when to make the h1 header. I am curious to see the behavior this time.</p></article>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-20 2:25:08">Thursday, December 20, 2018 02:25:08</time></h2><p>one more test for now to see if the header issue is really still an issue! typing from command line for this one. was doing some testing here before so why not amirite?!</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-20 3:07:53">Thursday, December 20, 2018 03:07:53</time></h2><p>updates!<br><ul><li>fixed or proved that header issue not currently an issue; not sure how or when that was fixed since it looked like it was recurring or persisting just a couple of test entries ago! We'll see if it keeps happening.</li><li>updated git bloggingModule repo! Yay!</li></ul><br><br><p>Here is how I was able to update the bloggingModule remote repository according to the git-related link in the list of references from yesterday :):</p><br><code>git add *<br>git commit -m "commit message"<br>git push origin master<br></code><br><br>I really need to fix the code chunks I have written because they are not ending up formatted in a way that looks nice to me. I think I know how I want it to look so I guess I'm just going to need to play around with it for a bit. OH another thing I really want to do soon is make this module into something that I can launch more easily, maybe with a .exe or something similar I can double click or find in a menu somewhere? I dunno. OH OH and I want to create some kind of menu that, in this GUI, has smilies and other options for journal entry features that I use on a regular basis so that I don't have to type that html out all of the time. :) EX: buttons for less than/greater than symbols, smiley faces etc. I would still like to add in some menus for the bloggule (bloggingModule gui), too, since it feels unnatural to not see them, and, it makes me uncomfortable not having a save option in here. hmmm maybe I should keep thinking about this some more; I really do enjoy how the lack of menus prevents certain actions that may make things complicated or introduce new bugs I'll be tempted to focus on before I achieve other goals. :P</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-20 3:26:37">Thursday, December 20, 2018 03:26:37</time></h2><p>yet another test in the gui; I am trying out a tiny bug fix I just made to the bloggingModule that keeps all of the user alerts about pasting in one function, long story short. after I test the alert from the command line I will update the remote repository again.</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-20 3:27:05">Thursday, December 20, 2018 03:27:05</time></h2><p>bloop bloop!</p></section>
<hr><article><h1 class="dateHeader"><time datetime="2018-12-23 16:44:25">Sunday, December 23, 2018 16:44:25</time></h1><p>Hey now, I just opened up the GUI to write my first entry in a few days (sorry about that, by the way; I have been busy for the holidays) and have experienced the same issue that was happening previously with the focus not being on the text field, meaning that I had to click inside this text box in order to begin typing this entry. Why is the issue only seemingly occurring intermittently?! Lame. Anyway, in spite of the hectic holidays (that have been really overall pretty great, to be honest, especially when you compare them to previous holidays; I have been able to remain surprisingly focused and calm, in spite of certain stressors and issues that have arisen, which just has not been possible consistently during the past several holiday seasons. Breakthrough!), I have been busy at work on the site, specifically, my journal and to do list, and, more specifically, I would say I have been working on lots of CSS to mark off some items in the to do list related to beautification or improved readability in the navigation header and to do list. For example, I did some stuff to the buttons on the to do list page to make them toggle, meaning I was able to reduce the original number of buttons by half because I was finally able to consolidate the toggle actions into one button per task status (to better illustrate the issue with the buttons before: previously, I had one button to hide a done task and another separate button to show a done task, and I knew it could all be done by one button but I wanted to get it done quickly more badly than I wanted to learn immediately how to toggle items with one button so I easily and quickly found the way to show and hide things with jquery and used those two separate functions with two separate buttons to show and hide things, telling myself that I would go back later to consolidate the two actions by doing additional research, which has been happening since around the time my holiday vacation started last week). I also added a few items to the list and have just discovered that here is no scroll bar on the right side of the blogging module GUI! I could have sworn I included code to have one of those! Uhhh I might have to add this to the to do list. You should look at the list. It has changed since for the first time in a little while. :) I got a little inspired today by some of the code changes I was making and how some of them turned out! Huzzah!</p></article>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-23 17:06:41">Sunday, December 23, 2018 17:06:41</time></h2><p><h3>part 1</h3>I wanted to go into more detail about the improvements I have been making over the past several days to the different pages and the blogging module. i also wanted to talk a bit about other goals accomplished (and some of them have been marked off of the to do list) that are related to the site! I have been surprisnigly productive this holiday season, mostly with respect to this site, and, as I mark items off of my checklist and work toward achieving those aforementioned, related goals, I also end up either discovering or introducing bugs that I also work to fix as I try to achieve the goals, ya know? This is my way of saying/justifying that I am also likely going to attempt to list here as many of the recently discovered and fixed bugs as possible, especially since some of them never made it to the to do list at all since they were so quickly fixed?! I also really should add an item to the to do list to prevent accidental up arrow induced loss of journal entries while using this blogging module in the command line because that just happened to me here tonight. :/<br><div><p>end of first part of second entry for today because I am afraid I might lose another entry again. :D :( :P</p></div></p></section>
<hr><article><h1 class="dateHeader"><time datetime="2018-12-27 19:19:08">Thursday, December 27, 2018 19:19:08</time></h1><p>It has been several days since I last worked on any part of any of this site. I have been trying to focus on good times with family and have been quite successful! Anyway, tonight, all I can think about is food and that I think I have been feeling lots of pressure to make lots of good progress on this site during these holiday vacations. It worked to my advantage intially while I had a lot of good ideas or bug fixes lined up to do for this site that makes sense; things started getting weird the last day I worked on this stuff when I realized that it might be impossible to use the time tags in the way I had wanted on the to do page as a way to mark when a task was first created and when the task was finally completed. I had hoped that I could add two time tags inside of a table (tr?) element, one for creation date, the other for completion date, but, while experimenting, I found that the formatting of the page got really messed up and that the time tags were not staying inside of the rows of the table that I put them in, which seems to suggest that they just do not belong in those rows. :( Maybe some more research of table rows or times would help? I dunno; what I do know is that I am sort of done for now with working on that idea and I am ready to work on a new and different one. :) I know! I should start working on fixing the bug in the gui and then adding the menu(s) that should be in the gui! :D I might finally make some progress on the menu of emoticons that I am currently missing. :P</p></article>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 19:41:37">Thursday, December 27, 2018 19:41:37</time></h2><p>arghblargh with this second entry for the journal today, in order to go ahead and fix the gui bug tonight that occurs upon closing the gui, i am reminded/still seeing the bug that prevents focus from being on this textbox; strangely, though, it looks like the focus is not in the shell, either! where the heck does it even go?!?!?!!?<br><br>While I'm here, I'd like to mention that I got to meet a new baby and also a cool cat and then hang out with both cool cats I know during my vacation this year. Both cats are women that are super sweet and funny. I have watched New Cat sleep all curled up on her side with a paw curled up under her chin. AW! her legs were stretched out in front of her. She was lying on her left side on the couch. OMG she twitches like a puppy in her sleep, y'all, and she is at least a year old. :P AWWW! okay let's see that bug again so I can more confidently kill it dead! Wish me luck! OH DAMN I am also reminded tonight that I should mark off the new trash/impossible? tasks I added to the to do list last time I fiddled with the site a few days ago AND that there is another bug having to do with a lack of scroll bar in this dang gui that still has bugs all in it! Ack!<br><br>Guys, one last thing: in case you never get to try it out yourself, my blogging module gui is called "Bloggule." :D I enjoy this name quite a bit for now.</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 20:25:37">Thursday, December 27, 2018 20:25:37</time></h2><p>another test of the bloggule here and heeyyy suddenly since this latest attempt to fix the bug that causes the nasty red error message text upon OKing to close i see that suddenly the focus is appearing in this textbox! huzzah! if this magical, sudden fix persists the the next bloggule (gui) issue I can focus on can be just the scroll bar! Huzzah!</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 20:34:32">Thursday, December 27, 2018 20:34:32</time></h2><p>still fighting with red-text-message-when-ok-to-close-in-bloggule bug; by the way, it seems that when I run this bloggule command a first time in an instance of powershell, the no-focus-in-textbox bug occurs, BUT the second and the rest of the times I run the same command, suddenly, the focus appears in the text box when the bloggule is started. WOW/frustrating!</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 20:40:40">Thursday, December 27, 2018 20:40:40</time></h2><p>heyyyy, haha so I was able to fix the bug that causes red error message text with info from <a href="https://social.technet.microsoft.com/Forums/en-US/5388624d-73d1-46d5-9944-d9143af50ca2/unable-to-find-type-systemwindowsmessagebox-runs-in-ise-but-not-from-powershell?forum=winserverpowershell">a forum conversation about the error message I was seeing</a>. The solution, apparently, is to add this code to the bloggingModule psm1 file:<br><br><code>Add-Type -AssemblyName PresentationFramework</code><br><br>I am also seeing that, running the bloggule in this fresh instance of powershell that is finally not showing the red error message text (which is confusing since I believe I had tried this code previously but after having tried another fix in the code without trying to run the freshly updated module in a brand new instance of powershell), the text in the text box is much smaller than usual, along with the entire bloggule gui box. It still appears in the center of the screen when it opens but the entire gui seems much smaller with this latest bug fix. :O</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 20:55:17">Thursday, December 27, 2018 20:55:17</time></h2><p>a;jsdlkfja;lskdjfasldkfjal;skdjf;alskdj oh heck yeah, I seem to have successfully fixed the bug with scrollbars not appearing with info from <a href="https://stackoverflow.com/questions/41869700/how-to-set-a-textbox-to-allow-multiple-lines-and-scrollability">this stackoverflow question about the same</a> and while I fixed that bug I also went ahead and changed the text sizes all to the same size so that I do not have to wonder so much what they should all look like and why one should look so different from the other. I'm honestly not even sure what the text would have looked like otherwise, honestly. <br><br>While I am super anxious to test out the scrollbar functionality in this bloggule gui, i'm not sure it makes sense for me to try to type enough text in here to do that? LOL the unfortunate effect of having shrunk down the text size is that it will take me longer to fill up the text box haa I had not considered this before making the size change. Aw well! Success! Learning! EXPOSURE! WAAAAHHHHHHH!!!!!!</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 21:46:12">Thursday, December 27, 2018 21:46:12</time></h2><p>I had to change the font back to what it was before and I think there is some bug related to font size (or maybe the change isn't taking because I am working in the same instance of powershell that I was working in before I saved the latest change to fix the font size since adding scroll bar along the side) AND OHHHH NOOOOO I AM NO LONGER ABLE TO MANUALLY RESIZE THE WINDOW BY DRAGGING THE BOTTOM RIGHT CORNER OF THE BOX!!! AND I FOUND A NEW BUG WHEN ENTERING AN EMPTY STRING IN THE GUI! I DID IT BY JUST PRESSING CANCEL INSTEAD OF TYPING ANYTHING IN!!!</p></section>
<hr><section><h2 class="dateHeader"><time datetime="2018-12-27 22:11:51">Thursday, December 27, 2018 22:11:51</time></h2><p>Focus is not auto focusing on the textbox in the bloggule gui even though I open the bloggule a second or third time in the same instance of powershell. :/</p></section>
<hr><article><h1 class="dateHeader"><time datetime="2019-01-01 0:48:53">Tuesday, January 1, 2019 00:48:53</time></h1><p>happy new year! too lazy to properly capitalize letters for now and you <i>know</i> I practice good punctualization inconsistently! aaaaanyway, i still need to add menus to the old bloggule, I still need to fix the dang focus bug...I am honestly just really struggling to get my mind back in all of my outstanding tasks because I'm extra tired today. :P extra tired today.</p></article>
<hr><article><h1 class="dateHeader"><time datetime="2019-01-01 0:54:06">Tuesday, January 1, 2019 00:54:06</time></h1><p>testing testing the command line again I am reminded that I still need to update the git code for the site and the powershell for bloggingModule and what not AND I still need to finish adding in the confirmation step when pressing enter to copy and paste after typing the journal entry and wowee there might need to be a cancel option for the command line version of the bloggingmodule or maybe i am working to hard to make the command line version too fancy/too much like a gui. maybe command line versions of things shouldn't be so user friendly all the time in the way that i always want to make them.</p></article>



  </article>
			</div>
        </div> <!-- #main-container -->

        <footer>
		  <?php require '/home/public/footer.php';?>
        </footer>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->

    </body>
</html>